### ISSUE TITLE
git-secret unable to run

### ISSUE THREAD

**Issue by hidden-dimensions** [oursky/devsecops-ci#64]
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from scanner import GitScanner
  File "/usr/local/devsecops-ci/git-secret/scanner.py", line 2, in <module>
    from git import Repo
  File "/usr/local/lib/python3.7/site-packages/git/__init__.py", line 38, in <module>
    from git.exc import *                       # @NoMove @IgnorePep8
  File "/usr/local/lib/python3.7/site-packages/git/exc.py", line 9, in <module>
    from git.compat import UnicodeMixin, safe_decode, string_types
  File "/usr/local/lib/python3.7/site-packages/git/compat.py", line 16, in <module>
    from gitdb.utils.compat import (
ModuleNotFoundError: No module named 'gitdb.utils.compat'
make[1]: *** [Makefile:11: check] Error 1
```

**Comment by Harmon758** [comment]
See https://github.com/gitpython-developers/GitPython/issues/983.
